// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/apus-run/gala/components/mq (interfaces: ConsumerRegistry,ConsumerWorker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/registry.go -package=mocks . ConsumerRegistry,ConsumerWorker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	mq "github.com/apus-run/gala/components/mq"
	gomock "go.uber.org/mock/gomock"
)

// MockConsumerRegistry is a mock of ConsumerRegistry interface.
type MockConsumerRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerRegistryMockRecorder
	isgomock struct{}
}

// MockConsumerRegistryMockRecorder is the mock recorder for MockConsumerRegistry.
type MockConsumerRegistryMockRecorder struct {
	mock *MockConsumerRegistry
}

// NewMockConsumerRegistry creates a new mock instance.
func NewMockConsumerRegistry(ctrl *gomock.Controller) *MockConsumerRegistry {
	mock := &MockConsumerRegistry{ctrl: ctrl}
	mock.recorder = &MockConsumerRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerRegistry) EXPECT() *MockConsumerRegistryMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockConsumerRegistry) Register(worker []mq.ConsumerWorker) mq.ConsumerRegistry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", worker)
	ret0, _ := ret[0].(mq.ConsumerRegistry)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockConsumerRegistryMockRecorder) Register(worker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockConsumerRegistry)(nil).Register), worker)
}

// StartAll mocks base method.
func (m *MockConsumerRegistry) StartAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartAll indicates an expected call of StartAll.
func (mr *MockConsumerRegistryMockRecorder) StartAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAll", reflect.TypeOf((*MockConsumerRegistry)(nil).StartAll), ctx)
}

// MockConsumerWorker is a mock of ConsumerWorker interface.
type MockConsumerWorker struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerWorkerMockRecorder
	isgomock struct{}
}

// MockConsumerWorkerMockRecorder is the mock recorder for MockConsumerWorker.
type MockConsumerWorkerMockRecorder struct {
	mock *MockConsumerWorker
}

// NewMockConsumerWorker creates a new mock instance.
func NewMockConsumerWorker(ctrl *gomock.Controller) *MockConsumerWorker {
	mock := &MockConsumerWorker{ctrl: ctrl}
	mock.recorder = &MockConsumerWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerWorker) EXPECT() *MockConsumerWorkerMockRecorder {
	return m.recorder
}

// ConsumerCfg mocks base method.
func (m *MockConsumerWorker) ConsumerCfg(ctx context.Context) (*mq.ConsumerConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumerCfg", ctx)
	ret0, _ := ret[0].(*mq.ConsumerConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumerCfg indicates an expected call of ConsumerCfg.
func (mr *MockConsumerWorkerMockRecorder) ConsumerCfg(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerCfg", reflect.TypeOf((*MockConsumerWorker)(nil).ConsumerCfg), ctx)
}

// HandleMessage mocks base method.
func (m *MockConsumerWorker) HandleMessage(arg0 context.Context, arg1 *mq.MessageExt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMessage indicates an expected call of HandleMessage.
func (mr *MockConsumerWorkerMockRecorder) HandleMessage(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessage", reflect.TypeOf((*MockConsumerWorker)(nil).HandleMessage), arg0, arg1)
}
